import org.codexist.ruleengine.ruleentity.DailyDomainRequest;
global org.codexist.ruleengine.service.EmailService emailService;



rule "Check for high request count domains"
when
    $domainRequest : DailyDomainRequest(totalRequestCount > 2000)
then
    System.out.println("Domain: " + $domainRequest.getDomain() + " has exceeded the average request count.");
    emailService.sendDomainAlertEmail("furkansahinkulakiz@gmail.com", $domainRequest.getDomain(), $domainRequest.getTotalRequestCount());
end
